workflows:
  react-native-workflow:
    name: React Native Full Build
    max_build_duration: 60
    environment:
      vars:
        NODE_ENV: production
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Run tests
        script: |
          npm test
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -scheme IRL -configuration Release -workspace IRL.xcworkspace
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
      - ios/build/Release-iphoneos/*.ipa

